/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthenticatedUploadLazyImport = createFileRoute(
  '/_authenticated/upload',
)()
const AuthenticatedFeedLazyImport = createFileRoute('/_authenticated/feed')()
const AuthenticatedProfileIdLazyImport = createFileRoute(
  '/_authenticated/profile/$id',
)()
const AuthenticatedPostIdLazyImport = createFileRoute(
  '/_authenticated/post/$id',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthenticatedUploadLazyRoute = AuthenticatedUploadLazyImport.update({
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/upload.lazy').then((d) => d.Route),
)

const AuthenticatedFeedLazyRoute = AuthenticatedFeedLazyImport.update({
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/feed.lazy').then((d) => d.Route),
)

const AuthenticatedProfileIdLazyRoute = AuthenticatedProfileIdLazyImport.update(
  {
    path: '/profile/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/profile/$id.lazy').then((d) => d.Route),
)

const AuthenticatedPostIdLazyRoute = AuthenticatedPostIdLazyImport.update({
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/post/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdLazyImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedFeedLazyRoute: typeof AuthenticatedFeedLazyRoute
  AuthenticatedUploadLazyRoute: typeof AuthenticatedUploadLazyRoute
  AuthenticatedPostIdLazyRoute: typeof AuthenticatedPostIdLazyRoute
  AuthenticatedProfileIdLazyRoute: typeof AuthenticatedProfileIdLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFeedLazyRoute: AuthenticatedFeedLazyRoute,
  AuthenticatedUploadLazyRoute: AuthenticatedUploadLazyRoute,
  AuthenticatedPostIdLazyRoute: AuthenticatedPostIdLazyRoute,
  AuthenticatedProfileIdLazyRoute: AuthenticatedProfileIdLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AuthenticatedRouteWithChildren
  '/feed': typeof AuthenticatedFeedLazyRoute
  '/upload': typeof AuthenticatedUploadLazyRoute
  '/post/$id': typeof AuthenticatedPostIdLazyRoute
  '/profile/$id': typeof AuthenticatedProfileIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AuthenticatedRouteWithChildren
  '/feed': typeof AuthenticatedFeedLazyRoute
  '/upload': typeof AuthenticatedUploadLazyRoute
  '/post/$id': typeof AuthenticatedPostIdLazyRoute
  '/profile/$id': typeof AuthenticatedProfileIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedLazyRoute
  '/_authenticated/upload': typeof AuthenticatedUploadLazyRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdLazyRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/feed' | '/upload' | '/post/$id' | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/feed' | '/upload' | '/post/$id' | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/feed'
    | '/_authenticated/upload'
    | '/_authenticated/post/$id'
    | '/_authenticated/profile/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/feed",
        "/_authenticated/upload",
        "/_authenticated/post/$id",
        "/_authenticated/profile/$id"
      ]
    },
    "/_authenticated/feed": {
      "filePath": "_authenticated/feed.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/upload": {
      "filePath": "_authenticated/upload.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/post/$id": {
      "filePath": "_authenticated/post/$id.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/$id": {
      "filePath": "_authenticated/profile/$id.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
