/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedUploadImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSuggestedImport } from './routes/_authenticated/suggested'
import { Route as AuthenticatedFollowingImport } from './routes/_authenticated/following'
import { Route as AuthenticatedFeedImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedProfileIdImport } from './routes/_authenticated/profile/$id'
import { Route as AuthenticatedPostIdImport } from './routes/_authenticated/post/$id'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUploadRoute = AuthenticatedUploadImport.update({
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSuggestedRoute = AuthenticatedSuggestedImport.update({
  path: '/suggested',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFollowingRoute = AuthenticatedFollowingImport.update({
  path: '/following',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFeedRoute = AuthenticatedFeedImport.update({
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileIdRoute = AuthenticatedProfileIdImport.update({
  path: '/profile/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPostIdRoute = AuthenticatedPostIdImport.update({
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/following': {
      id: '/_authenticated/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AuthenticatedFollowingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/suggested': {
      id: '/_authenticated/suggested'
      path: '/suggested'
      fullPath: '/suggested'
      preLoaderRoute: typeof AuthenticatedSuggestedImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFollowingRoute: typeof AuthenticatedFollowingRoute
  AuthenticatedSuggestedRoute: typeof AuthenticatedSuggestedRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFollowingRoute: AuthenticatedFollowingRoute,
  AuthenticatedSuggestedRoute: AuthenticatedSuggestedRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/suggested': typeof AuthenticatedSuggestedRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/suggested': typeof AuthenticatedSuggestedRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/following': typeof AuthenticatedFollowingRoute
  '/_authenticated/suggested': typeof AuthenticatedSuggestedRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/feed'
    | '/following'
    | '/suggested'
    | '/upload'
    | '/post/$id'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/feed'
    | '/following'
    | '/suggested'
    | '/upload'
    | '/post/$id'
    | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/feed'
    | '/_authenticated/following'
    | '/_authenticated/suggested'
    | '/_authenticated/upload'
    | '/_authenticated/post/$id'
    | '/_authenticated/profile/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/feed",
        "/_authenticated/following",
        "/_authenticated/suggested",
        "/_authenticated/upload",
        "/_authenticated/post/$id",
        "/_authenticated/profile/$id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_authenticated/feed": {
      "filePath": "_authenticated/feed.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/following": {
      "filePath": "_authenticated/following.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/suggested": {
      "filePath": "_authenticated/suggested.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/upload": {
      "filePath": "_authenticated/upload.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/post/$id": {
      "filePath": "_authenticated/post/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/$id": {
      "filePath": "_authenticated/profile/$id.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
